// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WindowsServiceXML.Context;

namespace WindowsServiceXML.Migrations
{
    [DbContext(typeof(Contextt))]
    [Migration("20231201122638_cc")]
    partial class cc
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WindowsServiceXML.Entity.CountryInfo", b =>
                {
                    b.Property<string>("sISOCode")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("sCapitalCity");

                    b.Property<string>("sContinentCode");

                    b.Property<string>("sCountryFlag");

                    b.Property<string>("sCurrencyISOCode");

                    b.Property<string>("sName");

                    b.Property<string>("sPhoneCode");

                    b.HasKey("sISOCode");

                    b.ToTable("CountryInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
